/* eslint-disable camelcase */

export const GPT_MODELS = [
  'gpt-3.5-turbo-0613',
  'gpt-3.5-turbo-0301',
  'gpt-3.5-turbo',
  'gpt-3.5-turbo-16k',
  'gpt-3.5-turbo-16k-0613',
  'gpt-4',
  'gpt-4-0314',
  'gpt-4-0614',
  'gpt-4-32k',
  'gpt-4-32k-0314',
  'gpt-4-32k-0614',
  'gpt-4-turbo',
  'gpt-4o',
] as const;

export const OPENAI_MODELS = [...GPT_MODELS, 'text-davinci-003', 'text-davinci-002'] as const;

export type GPTModel = (typeof GPT_MODELS)[number];
export type OpenAIModel = (typeof OPENAI_MODELS)[number];

export const OPENAI_MODELS_TITLES: Record<OpenAIModel, string> = {
  'text-davinci-003': 'text-davinci-003',
  'text-davinci-002': 'text-davinci-002',
  'gpt-3.5-turbo-0613': 'gpt-3.5-turbo-0613',
  'gpt-3.5-turbo-0301': 'gpt-3.5-turbo-0301',
  'gpt-3.5-turbo': 'gpt-3.5-turbo (recommended)',
  'gpt-3.5-turbo-16k': 'gpt-3.5-turbo-16k',
  'gpt-3.5-turbo-16k-0613': 'gpt-3.5-turbo-16k-0613',
  'gpt-4': 'gpt-4',
  'gpt-4-0314': 'gpt-4-0314',
  'gpt-4-0614': 'gpt-4-0614',
  'gpt-4-32k': 'gpt-4-32k (testing)',
  'gpt-4-32k-0314': 'gpt-4-32k-0314 (testing)',
  'gpt-4-32k-0614': 'gpt-4-32k-0614 (testing)',
  'gpt-4-turbo': 'gpt-4-turbo',
  'gpt-4o': 'gpt-4o',
} as const;

export const OPENAI_MODELS_DESCRIPTION: Record<OpenAIModel, string> = {
  'text-davinci-003': 'Text Davinci 003',
  'text-davinci-002': 'Text Davinci 002',
  'gpt-3.5-turbo-0613': 'GPT-3.5 Turbo 0613',
  'gpt-3.5-turbo-0301': 'GPT-3.5 Turbo 0301',
  'gpt-3.5-turbo': 'GPT-3.5 Turbo',
  'gpt-3.5-turbo-16k': 'GPT-3.5 Turbo 16K',
  'gpt-3.5-turbo-16k-0613': 'GPT-3.5 Turbo 16K 0613',
  'gpt-4': 'GPT-4',
  'gpt-4-0314': 'GPT-4 0314',
  'gpt-4-0614': 'GPT-4 0614',
  'gpt-4-32k': 'GPT-4 32K',
  'gpt-4-32k-0314': 'GPT-4 32K 0314',
  'gpt-4-32k-0614': 'GPT-4 32K 0614',
  'gpt-4-turbo': 'GPT-4 turbo',
  'gpt-4o': 'GPT-4o',
} as const;

export const LANGUAGES = {
  auto: 'Auto',
  'zh-Hans': '简体中文',
  'zh-Hant': '繁體中文',
  en: 'English',
  yue: '粵語',
  wyw: '漢文',
  ja: '日本語',
  ko: '한국어',
  fr: 'Français',
  de: 'Deutsch',
  es: 'Español',
  it: 'Italiano',
  ru: 'Русский',
  pt: 'Português',
  nl: 'Nederlands',
  pl: 'Polski',
  ar: 'العربية',
  af: 'Afrikaans',
  am: 'Amharic',
  az: 'Azerbaijani',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bn: 'Bengali',
  bs: 'Bosnian',
  ca: 'Catalan',
  ceb: 'Cebuano',
  co: 'Corsican',
  cs: 'Czech',
  cy: 'Welsh',
  da: 'Danish',
  el: 'Greek',
  eo: 'Esperanto',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  fi: 'Finnish',
  fj: 'Fijian',
  fy: 'Frisian',
  ga: 'Irish',
  gd: 'Scots Gaelic',
  gl: 'Galician',
  gu: 'Gujarati',
  ha: 'Hausa',
  haw: 'Hawaiian',
  he: 'Hebrew',
  hi: 'Hindi',
  hmn: 'Hmong',
  hr: 'Croatian',
  ht: 'Haitian Creole',
  hu: 'Hungarian',
  hy: 'Armenian',
  id: 'Indonesian',
  ig: 'Igbo',
  is: 'Icelandic',
  jw: 'Javanese',
  ka: 'Georgian',
  kk: 'Kazakh',
  km: 'Khmer',
  kn: 'Kannada',
  ku: 'Kurdish',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lo: 'Lao',
  lt: 'Lithuanian',
  lv: 'Latvian',
  mg: 'Malagasy',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  ne: 'Nepali',
  no: 'Norwegian',
  ny: 'Chichewa',
  or: 'Odia',
  pa: 'Punjabi',
  ps: 'Pashto',
  ro: 'Romanian',
  rw: 'Kinyarwanda',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  'sr-Cyrl': 'Serbian Cyrillic',
  'sr-Latn': 'Serbian Latin',
  st: 'Sesotho',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tr: 'Turkish',
  tt: 'Tatar',
  ug: 'Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
} as const;

export type Language = keyof typeof LANGUAGES;
